export const commentText = {
  sectionTitle: "Comments",
  sectionHint: "Thread supports up to 2 reply levels like Facebook",
  composerPlaceholder: "Write your comment...",
  replyPlaceholder: "Write a reply...",
  editPlaceholder: "Edit comment...",
  submit: "Post",
  saveEdit: "Save",
  cancel: "Cancel",
  loadMoreComments: "View more comments",
  loadMoreReplies: "View replies",
  collapseReplies: "Hide replies",
  emptyTitle: "No comments yet",
  emptyDescription:
    "Start the conversation with a short comment or attach media if you want.",
  errorTitle: "Could not load comments",
  errorDescription:
    "The comment list is not ready yet. You can still continue building the UI and handle local interactions here.",
  ownerBadge: "You",
  actionReply: "Reply",
  actionEdit: "Edit",
  actionDelete: "Delete",
  actionDeleting: "Deleting...",
  actionLike: "Like",
  mediaImageLabel: "Image",
  mediaVideoLabel: "Video",
  mediaAudioLabel: "Audio",
  mediaAlt: "Comment media",
  replyToPrefix: "Replying to",
  validationRequired: "Please enter content or select media before sending.",
  justNow: "Just now",
  emptyInline: "Be the first to comment on this post!",
  noMoreComments: "No more comments",
  emptyReplies: "No replies yet.",
  loading: {
    delete: "Deleting comment...",
  },
  errors: {
    resolveUpdatePayload: "Could not resolve comment update payload",
  },
}
