export const post = {
  savePost: "Save post",
  unsavePost: "Unsave post",
  actionComment: "Comment",
  actionShare: "Share",
  actionLike: "Like",
  statsReaction: "reactions",
  statsSave: "saves",
  statsComment: "comments",
  statsShare: "shares",
  fallbackAuthorName: "User",
  mediaAlt: "Post media",
  mediaPlayTooltip: "Play",
  menu: {
    pin: "Pin post",
    unpin: "Unpin post",
    edit: "Edit post",
    delete: "Delete post",
  },
  list: {
    userEmpty: "This user has no posts yet",
    savedEmpty: "You have not saved any posts yet",
    feedEmpty: "The feed currently has no posts",
    loadMore: "Load more",
  },
  loading: {
    save: "Saving post...",
    unsave: "Removing saved post...",
    pin: "Pinning post...",
    unpin: "Unpinning post...",
    delete: "Deleting post...",
    share: "Sharing post...",
    unshare: "Removing shared post...",
  },
}
