export const EMOJI = {
  smileys: [
    { char: "😀", label: "Cười lớn" },
    { char: "😃", label: "Cười tươi" },
    { char: "😄", label: "Cười hở răng" },
    { char: "😁", label: "Cười rạng rỡ" },
    { char: "😆", label: "Cười nhăn mắt" },
    { char: "😅", label: "Cười toát mồ hôi" },
    { char: "😂", label: "Cười ra nước mắt" },
    { char: "🤣", label: "Lăn ra cười" },
    { char: "😊", label: "Cười nhẹ" },
    { char: "🙂", label: "Cười mỉm" },
    { char: "🙃", label: "Cười ngược" },
    { char: "😉", label: "Nháy mắt" },
    { char: "😌", label: "Hài lòng" },
    { char: "😍", label: "Yêu thích" },
    { char: "🥰", label: "Đáng yêu" },
    { char: "😘", label: "Gửi hôn" },
    { char: "😗", label: "Hôn nhẹ" },
    { char: "😙", label: "Hôn cười" },
    { char: "😚", label: "Hôn nhắm mắt" },
    { char: "😋", label: "Thèm ăn" },
    { char: "😛", label: "Le lưỡi" },
    { char: "😜", label: "Le lưỡi nháy mắt" },
    { char: "🤪", label: "Mặt ngớ ngẩn" },
    { char: "😝", label: "Le lưỡi nhăn mặt" },
    { char: "🤑", label: "Thích tiền" },
    { char: "🤗", label: "Ôm" },
    { char: "🤭", label: "Che miệng cười" },
    { char: "🤫", label: "Suỵt" },
    { char: "🤔", label: "Suy nghĩ" },
    { char: "🤐", label: "Im lặng" }
  ],
  sad: [
  { char: "😔", label: "Buồn" },
  { char: "😟", label: "Lo lắng" },
  { char: "😕", label: "Bối rối" },
  { char: "🙁", label: "Hơi buồn" },
  { char: "☹️", label: "Buồn rầu" },
  { char: "😣", label: "Khó chịu" },
  { char: "😖", label: "Đau khổ" },
  { char: "😫", label: "Mệt mỏi" },
  { char: "😩", label: "Kiệt sức" },
  { char: "🥺", label: "Năn nỉ" },
  { char: "😢", label: "Khóc nhẹ" },
  { char: "😭", label: "Khóc lớn" },
  { char: "😤", label: "Hậm hực" },
  { char: "😠", label: "Tức giận" },
  { char: "😡", label: "Giận dữ" },
  { char: "🤬", label: "Chửi thề" },
  { char: "😱", label: "Sợ hãi" },
  { char: "😨", label: "Hoảng sợ" },
  { char: "😰", label: "Lo sợ" },
  { char: "😥", label: "Buồn nhẹ" },
  { char: "😓", label: "Đổ mồ hôi" },
  { char: "🤯", label: "Nổ não" },
  { char: "😳", label: "Ngượng" },
  { char: "🥵", label: "Nóng bức" },
  { char: "🥶", label: "Lạnh cóng" },
  { char: "😴", label: "Buồn ngủ" },
  { char: "🤤", label: "Chảy dãi" },
  { char: "😪", label: "Ngáp ngủ" },
  { char: "😵", label: "Chóng mặt" },
  { char: "🫠", label: "Tan chảy" }
  ],
  hands: [
  { char: "👋", label: "Vẫy tay" },
  { char: "🤚", label: "Giơ tay" },
  { char: "🖐️", label: "Bàn tay mở" },
  { char: "✋", label: "Dừng lại" },
  { char: "🖖", label: "Chào Vulcan" },
  { char: "👌", label: "OK" },
  { char: "🤌", label: "Chụm tay" },
  { char: "🤏", label: "Nhỏ xíu" },
  { char: "✌️", label: "Chiến thắng" },
  { char: "🤞", label: "Cầu may" },
  { char: "🤟", label: "Yêu thương" },
  { char: "🤘", label: "Rock" },
  { char: "🤙", label: "Gọi tôi" },
  { char: "👈", label: "Chỉ trái" },
  { char: "👉", label: "Chỉ phải" },
  { char: "👆", label: "Chỉ lên" },
  { char: "👇", label: "Chỉ xuống" },
  { char: "☝️", label: "Một" },
  { char: "👍", label: "Thích" },
  { char: "👎", label: "Không thích" },
  { char: "✊", label: "Nắm đấm" },
  { char: "👊", label: "Đấm" },
  { char: "🤛", label: "Đấm trái" },
  { char: "🤜", label: "Đấm phải" },
  { char: "👏", label: "Vỗ tay" },
  { char: "🙌", label: "Giơ hai tay" },
  { char: "👐", label: "Mở hai tay" },
  { char: "🤲", label: "Đón nhận" },
  { char: "🙏", label: "Cảm ơn" },
  { char: "✍️", label: "Viết" }
  ],
  people: [
    { char: "👶", label: "Em bé" },
    { char: "🧒", label: "Trẻ em" },
    { char: "👦", label: "Bé trai" },
    { char: "👧", label: "Bé gái" },
    { char: "🧑", label: "Người" },
    { char: "👨", label: "Đàn ông" },
    { char: "👩", label: "Phụ nữ" },
    { char: "🧓", label: "Người cao tuổi" },
    { char: "👴", label: "Ông lão" },
    { char: "👵", label: "Bà lão" },
    { char: "👨‍⚕️", label: "Bác sĩ nam" },
    { char: "👩‍⚕️", label: "Bác sĩ nữ" },
    { char: "👨‍🎓", label: "Sinh viên nam" },
    { char: "👩‍🎓", label: "Sinh viên nữ" },
    { char: "👨‍🏫", label: "Giáo viên nam" },
    { char: "👩‍🏫", label: "Giáo viên nữ" },
    { char: "👨‍💻", label: "Lập trình viên nam" },
    { char: "👩‍💻", label: "Lập trình viên nữ" },
    { char: "👨‍🍳", label: "Đầu bếp nam" },
    { char: "👩‍🍳", label: "Đầu bếp nữ" },
    { char: "👮", label: "Cảnh sát" },
    { char: "🕵️", label: "Thám tử" },
    { char: "💂", label: "Vệ binh" },
    { char: "👷", label: "Công nhân" },
    { char: "🤴", label: "Hoàng tử" },
    { char: "👸", label: "Công chúa" },
    { char: "🧙", label: "Pháp sư" },
    { char: "🧛", label: "Ma cà rồng" },
    { char: "🧟", label: "Xác sống" },
    { char: "🧝", label: "Tiên" }
  ],
  animals: [
    { char: "🐶", label: "Chó" },
    { char: "🐱", label: "Mèo" },
    { char: "🐭", label: "Chuột" },
    { char: "🐹", label: "Hamster" },
    { char: "🐰", label: "Thỏ" },
    { char: "🦊", label: "Cáo" },
    { char: "🐻", label: "Gấu" },
    { char: "🐼", label: "Gấu trúc" },
    { char: "🐨", label: "Koala" },
    { char: "🐯", label: "Hổ" },
    { char: "🦁", label: "Sư tử" },
    { char: "🐮", label: "Bò" },
    { char: "🐷", label: "Heo" },
    { char: "🐸", label: "Ếch" },
    { char: "🐵", label: "Khỉ" },
    { char: "🐔", label: "Gà" },
    { char: "🐧", label: "Chim cánh cụt" },
    { char: "🐦", label: "Chim" },
    { char: "🐤", label: "Gà con" },
    { char: "🦆", label: "Vịt" },
    { char: "🦅", label: "Đại bàng" },
    { char: "🦉", label: "Cú" },
    { char: "🐺", label: "Sói" },
    { char: "🐗", label: "Lợn rừng" },
    { char: "🐴", label: "Ngựa" },
    { char: "🦄", label: "Kỳ lân" },
    { char: "🐝", label: "Ong" },
    { char: "🐛", label: "Sâu" },
    { char: "🦋", label: "Bướm" },
    { char: "🐢", label: "Rùa" }
  ],
  food: [
    { char: "🍎", label: "Táo" },
    { char: "🍌", label: "Chuối" },
    { char: "🍇", label: "Nho" },
    { char: "🍓", label: "Dâu tây" },
    { char: "🍉", label: "Dưa hấu" },
    { char: "🍍", label: "Dứa" },
    { char: "🥭", label: "Xoài" },
    { char: "🍑", label: "Đào" },
    { char: "🍒", label: "Anh đào" },
    { char: "🥑", label: "Bơ" },
    { char: "🍅", label: "Cà chua" },
    { char: "🥕", label: "Cà rốt" },
    { char: "🌽", label: "Bắp" },
    { char: "🍞", label: "Bánh mì" },
    { char: "🥖", label: "Bánh mì baguette" },
    { char: "🥐", label: "Bánh sừng bò" },
    { char: "🧀", label: "Phô mai" },
    { char: "🍗", label: "Đùi gà" },
    { char: "🍖", label: "Sườn nướng" },
    { char: "🍔", label: "Hamburger" },
    { char: "🍟", label: "Khoai tây chiên" },
    { char: "🍕", label: "Pizza" },
    { char: "🌭", label: "Xúc xích" },
    { char: "🥪", label: "Bánh sandwich" },
    { char: "🍜", label: "Mì" },
    { char: "🍣", label: "Sushi" },
    { char: "🍩", label: "Bánh donut" },
    { char: "🍪", label: "Bánh quy" },
    { char: "🍰", label: "Bánh kem" },
    { char: "🍫", label: "Sô-cô-la" }
  ],
  travel: [
    { char: "🚗", label: "Ô tô" },
    { char: "🚕", label: "Taxi" },
    { char: "🚌", label: "Xe buýt" },
    { char: "🚎", label: "Xe điện" },
    { char: "🏎️", label: "Xe đua" },
    { char: "🚓", label: "Xe cảnh sát" },
    { char: "🚑", label: "Xe cứu thương" },
    { char: "🚒", label: "Xe cứu hỏa" },
    { char: "🚜", label: "Máy kéo" },
    { char: "✈️", label: "Máy bay" },
    { char: "🚀", label: "Tên lửa" },
    { char: "🚁", label: "Trực thăng" },
    { char: "🚢", label: "Tàu thủy" },
    { char: "⛵", label: "Thuyền buồm" },
    { char: "🚤", label: "Ca nô" },
    { char: "🏠", label: "Nhà" },
    { char: "🏡", label: "Nhà vườn" },
    { char: "🏢", label: "Tòa nhà" },
    { char: "🏬", label: "Trung tâm thương mại" },
    { char: "🏥", label: "Bệnh viện" },
    { char: "🏫", label: "Trường học" },
    { char: "🏰", label: "Lâu đài" },
    { char: "🗼", label: "Tháp" },
    { char: "🗽", label: "Tượng Nữ thần Tự do" },
    { char: "🌋", label: "Núi lửa" },
    { char: "⛰️", label: "Núi" },
    { char: "🏖️", label: "Bãi biển" },
    { char: "🏜️", label: "Sa mạc" },
    { char: "🌅", label: "Hoàng hôn" },
    { char: "🌉", label: "Cầu" }
  ],
  objects: [
    { char: "📱", label: "Điện thoại" },
    { char: "💻", label: "Laptop" },
    { char: "🖥️", label: "Máy tính bàn" },
    { char: "⌨️", label: "Bàn phím" },
    { char: "🖱️", label: "Chuột máy tính" },
    { char: "🖨️", label: "Máy in" },
    { char: "📷", label: "Máy ảnh" },
    { char: "📹", label: "Máy quay phim" },
    { char: "📺", label: "Tivi" },
    { char: "🎧", label: "Tai nghe" },
    { char: "🎤", label: "Micro" },
    { char: "🎮", label: "Tay cầm game" },
    { char: "⌚", label: "Đồng hồ" },
    { char: "💡", label: "Bóng đèn" },
    { char: "🔦", label: "Đèn pin" },
    { char: "🔋", label: "Pin" },
    { char: "🔌", label: "Ổ cắm điện" },
    { char: "💰", label: "Túi tiền" },
    { char: "💎", label: "Kim cương" },
    { char: "🔑", label: "Chìa khóa" },
    { char: "🧰", label: "Hộp dụng cụ" },
    { char: "🪑", label: "Ghế" },
    { char: "🛏️", label: "Giường" },
    { char: "🚪", label: "Cửa" },
    { char: "🧴", label: "Chai" },
    { char: "🧸", label: "Gấu bông" },
    { char: "🎁", label: "Quà tặng" },
    { char: "📦", label: "Hộp" },
    { char: "🧾", label: "Biên lai" },
    { char: "📌", label: "Ghim" }
  ],
  symbols: [
    { char: "❤️", label: "Trái tim đỏ" },
    { char: "💛", label: "Trái tim vàng" },
    { char: "💚", label: "Trái tim xanh lá" },
    { char: "💙", label: "Trái tim xanh dương" },
    { char: "💜", label: "Trái tim tím" },
    { char: "🤍", label: "Trái tim trắng" },
    { char: "🖤", label: "Trái tim đen" },
    { char: "💔", label: "Trái tim tan vỡ" },
    { char: "❣️", label: "Dấu chấm than trái tim" },
    { char: "💕", label: "Hai trái tim" },
    { char: "💞", label: "Trái tim xoay" },
    { char: "💓", label: "Trái tim đập" },
    { char: "💗", label: "Trái tim lớn dần" },
    { char: "💖", label: "Trái tim lấp lánh" },
    { char: "💘", label: "Trái tim mũi tên" },
    { char: "💝", label: "Trái tim ruy băng" },
    { char: "⭐", label: "Ngôi sao" },
    { char: "🌟", label: "Ngôi sao sáng" },
    { char: "✨", label: "Lấp lánh" },
    { char: "⚡", label: "Tia sét" },
    { char: "🔥", label: "Ngọn lửa" },
    { char: "💥", label: "Bùng nổ" },
    { char: "☀️", label: "Mặt trời" },
    { char: "🌙", label: "Mặt trăng" },
    { char: "☁️", label: "Mây" },
    { char: "🌈", label: "Cầu vồng" },
    { char: "🎵", label: "Nốt nhạc" },
    { char: "🔔", label: "Chuông" },
    { char: "🎉", label: "Ăn mừng" },
    { char: "💯", label: "100 điểm" }
  ]
}

export const REACTION_META = {
  LIKE: { label: "Thích", emoji: "👍", color: "#7cb2fe" },
  LOVE: { label: "Yêu thích", emoji: "❤️", color: "#F33E58" },
  HAHA: { label: "Haha", emoji: "😂", color: "#F7B125" },
  WOW: { label: "Wow", emoji: "😮", color: "#F7B125" },
  SAD: { label: "Buồn", emoji: "😢", color: "#F7B125" },
  ANGRY: { label: "Phẫn nộ", emoji: "😡", color: "#E9710F" },
};