export const LABEL = {
    EMAIL:"Email",
    PASSWORD:"Mật khẩu",
    RE_PASS:"Nhập lại mật khẩu",
    CONFIRM_PASS:"Xác nhận mật khẩu",
    DISPLAY_NAME:"Tên hiển thị",
    CREATE_PASS:"Mật khẩu",
    ERROR:"Lỗi !",
    CODE:"Mã xác minh",
    OLD_PASSWORD : "Mật khẩu cũ",
    NEW_PASSWORD : "Mật khẩu mới",
    USERNAME:"Tên người dùng",
    SAVE:"Lưu",
    FOLLOW:"Người theo dõi",
    FOLLOWING:"Người đang theo dõi",
    CLOSE:"Đóng",
    PROFILE:"Thông tin cá nhân",
    LOGOUT:"Đăng xuất",
    CHANGE_PASSWORD:"Đổi mật khẩu",
    CREATED_POSTS : "Danh sách bài viết đã tạo",
    SAVED_POSTS : "Danh sách bài viết đã lưu",
    FEED:"Xu hướng",
    FOLLOWING_POSTS:"Theo dõi",
    WRITE_COMMENT : "Viết bình luận...",
    EDIT_COMMENT : "Chỉnh sửa bình luận",
    DELETE_COMMENT : "Xóa bình luận",
    BACK_TO_LOGIN: "Quay về trang đăng nhập",
    PIN : "ghim bài viết",
    UNPIN : "bỏ ghim bài viết" ,
    EDIT: "Sửa",
    DELETE : "Xóa",
}