export const TEXT = {
    REDIRECT_REGISTER : "Bạn chưa có tài khoản?",
    REDIRECT_LOGIN : "Bạn đã có tài khoản?",
    REGISTER:"Đăng kí",
    LOGIN:"Đăng nhập",
    FORGOT:"Quên mật khẩu",
    BACK_TO_LOGIN:"Quay về đăng nhập",
    REQUEST_FORGOT : "Yêu cầu nhận lại mật khẩu",
    VERIFY_REGISTER_REQUEST : 'Vui lòng xác thực địa chỉ email bằng mã chúng tôi đã gửi',
    SEND_VERIFY : "Xác nhận",
    VALIDATION_SUCCESS : "Tài khoản của bạn đã xác minh thành công! Hãy quay về trang đăng nhập.",
    RESET_PASSWORD_VERIFY : "Chúng tôi đã gửi mã về email của bạn, hãy điền vào mã và mật khẩu muốn thay đổi",
    RECOMMEND_TO_BACK_TO_FORGOT_PAGE : "Hãy quay về trang quên mật khẩu để điền email!",
    RESET_PASSWORD_SUCCESSFULLY : "Mật khẩu của bạn đã được đặt lại thành công! Vui lòng đăng nhập lại",
}