export const TEXT = {
    REDIRECT_REGISTER : "Bạn chưa có tài khoản?",
    REDIRECT_LOGIN : "Bạn đã có tài khoản?",
    REGISTER:"Đăng kí",
    LOGIN:"Đăng nhập",
    FORGOT:"Quên mật khẩu",
    BACK_TO_LOGIN:"Quay về đăng nhập",
    REQUEST_FORGOT : "Yêu cầu nhận lại mật khẩu",
    VERIFY_REGISTER_REQUEST : 'Vui lòng xác thực địa chỉ email bằng mã chúng tôi đã gửi',
    SEND_VERIFY : "Xác nhận",
    VALIDATION_SUCCESS : "Tài khoản của bạn đã xác minh thành công! Hãy quay về trang đăng nhập.",
    RESET_PASSWORD_VERIFY : "Chúng tôi đã gửi mã về email của bạn, hãy điền vào mã và mật khẩu muốn thay đổi",
    RECOMMEND_TO_BACK_TO_FORGOT_PAGE : "Hãy quay về trang quên mật khẩu để điền email!",
    RESET_PASSWORD_SUCCESSFULLY : "Mật khẩu của bạn đã được đặt lại thành công! Vui lòng đăng nhập lại",
    CHANGE_PASSWORD_SUCCESSFULLY : "Mật khẩu của bạn đã được thay đổi thành công! Vui lòng đăng nhập lại",
    OLD_PASSWORD_INCORRECT: "Mật khẩu cũ không đúng",
    NO_NOTIFICATION : "Chưa có thông báo nào !",
    FOLLOW:"Theo dõi",
    UNFOLLOW:"Hủy theo dõi",
    NO_FOLLOWERS : "Chưa có người theo dõi !",
    NO_FOLLOWINGS : "Bạn chưa theo dõi ai !",
    CLIENT_FOLLOW: "Đang theo dõi",
    CLIENT_NO_FOLLOW:"Không theo dõi",
    NO_POST_CLIENT : "Người dùng này chưa có bài viết nào",
    NO_POST_ME : "Bạn chưa đăng bài viết nào",
    READ : "đã đọc",
    NOT_READ : "Thông báo mới !",
    NO_POST:"Chưa có bài viết nào !",
    NO_POST_SAVED:"Bạn chưa lưu bài viết nào",
    CREATE_POST_SUCCESS:"Tạo bài viết thành công!",
    NO_FEED : "Bảng tin chưa có bài viết nào mới",
    NO_FOLLOWING_POSTS : "Những người bạn theo dõi hiện chưa có bài đăng"
}