export const TITLE = {
    APP_NAME : "Threaddit",
    LOGIN_TITLE:"Đăng nhập vào Threddit",
    REGISTER_TITLE:"Đăng kí Threddit",
    FORGOT:"Quên mật khẩu",
    REGISTER_SUCCESS : "Đăng kí thành công",
    VALIDATION : "Xác minh tài khoản", 
    VALIDATION_SUCCESS : "Xác minh tài khoản thành công",
    LOGIN_FAIL : "Đăng nhập không thành công",
    RESET_PASSWORD_REQUEST : "Yêu cầu đặt lại mật khẩu không thành công",
    RESET_PASSWORD_VERIFY : "Đặt lại mật khẩu mật khẩu",
    RESET_PASSWORD : "Đặt lại mật khẩu" ,
    RESET_PASSWORD_SUCCESSFULLY : "Đặt lại mật khẩu thành công",
    RESET_PASSWORD_FAIL : "Đặt lại mật khẩu không thành công",
    SIGNOUT:"Đăng xuất",
    USER_INFO:"Thông tin cá nhân",
    ERROR:"Lỗi!",
    OK:"OK",
    CHANGE_NAME_SUCCESS:"Đổi tên thành công",
    CHANGE_NAME_FAIL : "Đổi tên không thành công",
    CHANGE_PASSWORD: "Đổi mật khẩu",
    CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
    CHANGE_PASSWORD_FAIL: "Đổi mật khẩu không thành công",
    NOTIFICATION:"Thông báo",
    FOLLOW_LIST : "Danh sách theo dõi",
    CREATE_POST_SUCCESS : "Tạo bài viết thành công",
    SEARCH:"Tìm kiếm"
}