const BASE = {
  black:'#0A0B0B',
  white: '#ffffff',
  gray: {
    100: '#f5f5f5',
    300: '#9c9c9c',
    500: '#6b6b6b'
  }
}

export const COLOR = {
  background:{
    surface:{
      default:'transparent',
      auth:{
        dark:'rgba(255,255,255,0.2)',
        light:'rgba(156, 156, 156, 0.4)'
      }
    },
    main:{
      dark:BASE.black,
      light:BASE.white,
    }
  },
  text:{
    primary:{
      dark:BASE.black,
      light:BASE.white,
    },
    secondary:{
      dark:BASE.black,
      light:BASE.white,
    },
    placeholder:{
      dark:'',
      light:'',
    }
  },
  button:{
    primary:{
      default:{
        bg:{
        dark:BASE.white,
        light:BASE.black,
        },
        text:{
          dark:BASE.black,
          light:BASE.white,
        },
        shadow:{
          dark:'rgba(0,0,0,0.25)',
          light:'rgba(0, 0, 0, 0.18)'
        },
      },
      disable:{
        bg:{
          dark:'#9a9a9aff',
          light:'#464646ff'
        },
        text:{
          dark:'#121212ff',
          light:'#c6c6c6ff'
        },
        shadow:{
          dark:'rgba(0,0,0,0.25)',
          light:'rgba(0, 0, 0, 0.18)'
        }
      }
    },
    google:{
      bg:BASE.white,
      shadow:{
        dark:BASE.black,
        light:'#757575ff'
      },
      border:{
        dark:'#676767ff',
        light:'#c2c2c2ff'
      },
      hover:'#cacacaff'
    }
  },
  textfield:{
    border:{
      default:{
        dark:'#C5C5C5',
        light:'#676767ff'
      },
      after:{
        dark:BASE.white,
        light:BASE.black
      },
      focus:{
        dark:BASE.white,
        light:BASE.black
      },
      error:{},
      hover:{},
      disable:{}
    },
    background:{
      default:{},
      focus:{}
    },
    text:{
      value:{dark:{},light:{}},
      placeholder:{
        dark:BASE.WHITE,
        light:BASE.BLACK
      },
      label:{
        default:{
          dark:'#C5C5C5',
          light:'#676767ff'
        },
        focus:{
          dark:BASE.white,
          light:BASE.black
        }
      }
    }
  },
  link:{
    primary:{
      default:{
        dark:BASE.white,
        light:BASE.black
      },
      hover:{
        dark:'#7deeffff',
        light:'#7738ffff'
      }
    },
    secondary:{
      default:{
        dark:'#62e2ffff',
        light:'#00b7e0ff'
      },
      hover:{
        dark:'#00D0FF',
        light:'#0499bbff'
      }
    }
  },
  divider:{
    dark:BASE.white,
    light:BASE.black
  },
  form_label:{
    dark:BASE.white,
    light:BASE.black
  },
  radio:{
    dark:BASE.white,
    light:BASE.black
  }
}