export const style = {
  block: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
      width: "max-content",
      minWidth: "100%",
      fontFamily: "inherit",
      fontSynthesis: "none",
      textRendering: "optimizeLegibility",
      "& .MuiTypography-root, & .MuiButtonBase-root, & .MuiButton-root, & .MuiInputBase-input": {
        fontFamily: "inherit",
        fontSynthesis: "none",
      },
    },
    row: {
      display: "flex",
      alignItems: "flex-start",
      gap: "0.7rem",
      width: "max-content",
      minWidth: "100%",
    },
    avatar: (level) => ({
      width: level === 0 ? "2.25rem" : "2rem",
      height: level === 0 ? "2.25rem" : "2rem",
      flexShrink: 0,
    }),
    body: {
      minWidth: "max-content",
      display: "flex",
      flexDirection: "column",
      gap: "0.38rem",
    },
    bubble: {
      alignSelf: "flex-start",
      position: "relative",
      display: "flex",
      flexDirection: "column",
      gap: "0.45rem",
      width: "fit-content",
      maxWidth: "42rem",
      borderRadius: "1rem",
      px: "0.8rem",
      py: "0.7rem",
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#1F232A" : "#F0F3F7"),
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#2E343D" : "#E0E6ED"),
    },
    bubbleHeader: {
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: "0.75rem",
    },
    bubbleMeta: {
      minWidth: 0,
      display: "flex",
      flexDirection: "row",
      gap: "0.4rem",
    },
    authorName: {
      fontSize: "0.92rem",
      fontWeight: 700,
      lineHeight: 1.2,
      wordBreak: "break-word",
    },
    ownerBadge: {
      alignSelf: "flex-start",
      px: "0.45rem",
      py: "0.12rem",
      borderRadius: "999rem",
      fontSize: "0.72rem",
      fontWeight: 600,
      color: (theme) => (theme.palette.mode === "dark" ? "#DDE6F0" : "#34506B"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#2A3340" : "#E7EFF8"),
    },
    time: {
      fontSize: "0.75rem",
      lineHeight: 1.3,
      color: (theme) => (theme.palette.mode === "dark" ? "#95A0AD" : "#6E7C8D"),
    },
    menuButton: {
      width: "1.8rem",
      height: "1.8rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#B7C0CA" : "#607082"),
    },
    text: {
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
      lineHeight: 1.55,
      fontSize: "0.92rem",
      fontWeight: 400,
    },
    replyTo: {
      fontSize: "0.8rem",
      lineHeight: 1.3,
      fontWeight: 600,
      color: (theme) => (theme.palette.mode === "dark" ? "#BDD7FF" : "#2F6AA3"),
    },
    actions: {
      display: "flex",
      alignItems: "center",
      gap: "0.85rem",
      flexWrap: "wrap",
      paddingLeft: "0.1rem",
    },
    actionButton: {
      minHeight: "1.65rem",
      px: "0.15rem",
      borderRadius: "999rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#AAB2BD" : "#667588"),
      fontSize: "0.82rem",
      fontWeight: 600,
      "&:hover": {
        backgroundColor: "transparent",
      },
    },
    editedLabel: {
      fontSize: "0.76rem",
      fontWeight: 600,
      color: (theme) => (theme.palette.mode === "dark" ? "#95A0AD" : "#7A8797"),
    },
    repliesWrap: {
      position: "relative",
      display: "flex",
      flexDirection: "column",
      gap: "0.85rem",
      marginTop: "0.05rem",
      marginLeft: "1rem",
      paddingLeft: "1rem",
      "&::before": {
        content: '""',
        position: "absolute",
        top: 0,
        bottom: 0,
        left: "0.2rem",
        width: "2px",
        borderRadius: "999rem",
        backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#2F3742" : "#D6DFE8"),
      },
    },
    repliesNotice: {
      alignSelf: "flex-start",
      px: "0.75rem",
      py: "0.55rem",
      borderRadius: "0.9rem",
      border: "1px dashed",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#3B4552" : "#D7E0EA"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#1B2027" : "#F8FBFD"),
    },
    repliesNoticeText: {
      fontSize: "0.8rem",
      lineHeight: 1.45,
      color: (theme) => (theme.palette.mode === "dark" ? "#C6D0DB" : "#52657A"),
    },
    repliesSentinel: {
      width: "100%",
      height: "1px",
    },
    repliesLoading: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      minHeight: "1.5rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#AEB9C7" : "#5E7288"),
    },
    repliesToggle: {
      alignSelf: "flex-start",
      minHeight: "1.8rem",
      px: "0.45rem",
      borderRadius: "999rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#C4D1DD" : "#435B73"),
      fontSize: "0.82rem",
      fontWeight: 600,
      "&:hover": {
        backgroundColor: "transparent",
      },
    },
    replyComposerWrap: {
      marginTop: "0.2rem",
    },
  },
};
