export const post = {
  savePost: "Lưu bài viết",
  unsavePost: "Hủy lưu bài viết",
  actionComment: "Bình luận",
  actionShare: "Chia sẻ",
  actionLike: "Thích",
  statsReaction: "lượt tương tác",
  statsSave: "Lượt lưu",
  statsComment: "bình luận",
  statsShare: "lượt chia sẻ",
  fallbackAuthorName: "Người dùng",
  mediaAlt: "Media bài viết",
  mediaPlayTooltip: "Phát",
  menu: {
    pin: "Ghim bài viết",
    unpin: "Hủy ghim bài viết",
    edit: "Chỉnh sửa bài viết",
    delete: "Xóa bài viết",
  },
  list: {
    userEmpty: "Người dùng này chưa có bài viết nào",
    savedEmpty: "Bạn chưa lưu bài viết nào",
    feedEmpty: "Hiện bảng tin chưa có bài viết nào",
    loadMore: "Tải thêm",
  },
  loading: {
    save: "Đang lưu bài viết...",
    unsave: "Đang bỏ lưu bài viết...",
    pin: "Đang ghim bài viết...",
    unpin: "Đang gỡ ghim bài viết...",
    delete: "Đang xóa bài viết...",
    share: "Đang chia sẻ bài viết...",
    unshare: "Đang hủy chia sẻ bài viết...",
  },
}
