export const style = {
  list: {
    root: (variant) => ({
      px: "1rem",
      pb: "1rem",
      pt: variant === "page" ? "0.9rem" : "0.75rem",
      display: "flex",
      flexDirection: "column",
      gap: "0.85rem",
    }),
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "0.75rem",
      flexWrap: "wrap",
    },
    headerMeta: {
      display: "flex",
      flexDirection: "column",
      gap: "0.2rem",
    },
    titleRow: {
      display: "flex",
      alignItems: "center",
      gap: "0.5rem",
      flexWrap: "wrap",
    },
    title: {
      fontSize: "1rem",
      fontWeight: 800,
      lineHeight: 1.2,
    },
    count: {
      px: "0.55rem",
      py: "0.15rem",
      borderRadius: "999rem",
      fontSize: "0.78rem",
      fontWeight: 700,
      color: (theme) => (theme.palette.mode === "dark" ? "#E7EAEE" : "#2A3340"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#2A2E35" : "#EEF3F8"),
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#3A3F46" : "#DCE4EE"),
    },
    hint: {
      fontSize: "0.82rem",
      lineHeight: 1.5,
      color: (theme) => (theme.palette.mode === "dark" ? "#A8B0BA" : "#677688"),
    },
    composerWrap: {
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#2E343C" : "#E2E8F0"),
      borderRadius: "1rem",
      px: "0.75rem",
      py: "0.68rem",
      background: (theme) =>
        theme.palette.mode === "dark"
          ? "linear-gradient(145deg, rgba(255,255,255,0.03) 0%, rgba(255,255,255,0.015) 100%)"
          : "linear-gradient(145deg, #FCFDFE 0%, #F6F9FC 100%)",
      boxShadow: (theme) =>
        theme.palette.mode === "dark"
          ? "0 10px 24px rgba(0,0,0,0.16)"
          : "0 10px 24px rgba(31,50,79,0.05)",
    },
    threadList: {
      display: "flex",
      flexDirection: "column",
      gap: "0.95rem",
    },
    loadMoreWrap: {
      display: "flex",
      justifyContent: "center",
      pt: "0.1rem",
    },
    loadMoreButton: {
      minHeight: "2.2rem",
      px: "1rem",
      borderRadius: "999rem",
      textTransform: "none",
      fontWeight: 700,
      boxShadow: "none",
    },
    emptyState: {
      border: "1px dashed",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#3D4450" : "#D9E1EB"),
      borderRadius: "1rem",
      px: "1rem",
      py: "1.15rem",
      textAlign: "center",
      display: "flex",
      flexDirection: "column",
      gap: "0.35rem",
      alignItems: "center",
    },
    emptyIcon: {
      fontSize: "1.45rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#C2CAD4" : "#506072"),
    },
    emptyTitle: {
      fontSize: "0.95rem",
      fontWeight: 700,
      lineHeight: 1.25,
    },
    emptyDescription: {
      maxWidth: "28rem",
      fontSize: "0.86rem",
      lineHeight: 1.55,
      color: (theme) => (theme.palette.mode === "dark" ? "#A8B0BA" : "#667587"),
    },
    skeletonList: {
      display: "flex",
      flexDirection: "column",
      gap: "0.85rem",
    },
    skeletonRow: {
      display: "flex",
      alignItems: "flex-start",
      gap: "0.75rem",
    },
    skeletonAvatar: {
      width: "2.25rem",
      height: "2.25rem",
      flexShrink: 0,
    },
    skeletonBubble: {
      flex: 1,
      borderRadius: "1rem",
      overflow: "hidden",
    },
    skeletonLinePrimary: {
      width: "42%",
      maxWidth: "10rem",
      height: "0.9rem",
      borderRadius: "999rem",
      mb: "0.55rem",
    },
    skeletonLineSecondary: {
      width: "100%",
      height: "0.78rem",
      borderRadius: "999rem",
      mb: "0.35rem",
    },
    skeletonLineShort: {
      width: "72%",
      height: "0.78rem",
      borderRadius: "999rem",
    },
    composerCard: (compact) => ({
      display: "flex",
      alignItems: "flex-start",
      gap: compact ? "0.5rem" : "0.6rem",
      ...(compact && {
        gap: "0.5rem",
      }),
    }),
    composerAvatar: (compact) => ({
      width: compact ? "2rem" : "2.35rem",
      height: compact ? "2rem" : "2.35rem",
      flexShrink: 0,
    }),
    composerBody: {
      minWidth: 0,
      flex: 1,
      display: "flex",
      flexDirection: "column",
      gap: "0.5rem",
    },
    composerTextarea: {
      "& .MuiOutlinedInput-root": {
        alignItems: "flex-start",
        borderRadius: "0.95rem",
        backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#20242B" : "#F0F3F7"),
      },
      "& .MuiOutlinedInput-notchedOutline": {
        borderColor: (theme) => (theme.palette.mode === "dark" ? "#313741" : "#D9E1EB"),
      },
      "& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
        borderColor: (theme) => (theme.palette.mode === "dark" ? "#46505D" : "#C7D4E2"),
      },
      "& .MuiInputBase-inputMultiline": {
        fontSize: "0.95rem",
        lineHeight: 1.45,
        padding: "0.58rem 0.78rem",
      },
    },
    composerReplyTag: {
      alignSelf: "flex-start",
      px: "0.55rem",
      py: "0.2rem",
      borderRadius: "999rem",
      fontSize: "0.74rem",
      fontWeight: 700,
      color: (theme) => (theme.palette.mode === "dark" ? "#D8E1EB" : "#3F5368"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#27303A" : "#EDF3F8"),
    },
    composerFooter: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: "0.55rem",
      flexWrap: "wrap",
    },
    composerTools: {
      display: "flex",
      alignItems: "center",
      gap: "0.35rem",
      flexWrap: "wrap",
    },
    composerEmojiWrap: {
      minHeight: "1.9rem",
      minWidth: "1.9rem",
      px: "0.55rem",
      borderRadius: "999rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      color: (theme) => (theme.palette.mode === "dark" ? "#D7DEE7" : "#45576B"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#232831" : "#EDF2F7"),
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#313844" : "#DCE5EF"),
    },
    composerToolButton: {
      minHeight: "1.9rem",
      minWidth: "1.9rem",
      px: "0.62rem",
      borderRadius: "999rem",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "0.35rem",
      color: (theme) => (theme.palette.mode === "dark" ? "#D7DEE7" : "#45576B"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#232831" : "#EDF2F7"),
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#313844" : "#DCE5EF"),
      cursor: "pointer",
      transition: "all 150ms ease",
      "&:hover": {
        backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#2E3641" : "#E7EEF6"),
      },
    },
    composerToolLabel: {
      fontSize: "0.75rem",
      fontWeight: 700,
      lineHeight: 1,
    },
    composerActions: {
      display: "flex",
      alignItems: "center",
      gap: "0.5rem",
      marginLeft: "auto",
    },
    composerCancelButton: {
      minHeight: "2rem",
      px: "0.85rem",
      borderRadius: "999rem",
      textTransform: "none",
      fontWeight: 700,
    },
    composerSubmitButton: {
      minHeight: "2rem",
      px: "0.95rem",
      borderRadius: "999rem",
      textTransform: "none",
      fontWeight: 700,
      boxShadow: "none",
    },
    mediaPreviewList: {
      display: "grid",
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
      gap: "0.55rem",
      width: "100%",
    },
    mediaPreviewItem: {
      position: "relative",
      borderRadius: "0.85rem",
      overflow: "hidden",
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#323A45" : "#DEE6EF"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#15181D" : "#FFFFFF"),
      minHeight: "7.25rem",
    },
    mediaPreviewVisual: {
      display: "block",
      width: "100%",
      height: "100%",
      minHeight: "7.25rem",
      objectFit: "cover",
      backgroundColor: "#000000",
    },
    mediaPreviewAudioWrap: {
      minHeight: "7.25rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      p: "0.75rem",
      background: (theme) =>
        theme.palette.mode === "dark"
          ? "linear-gradient(145deg, #171B21 0%, #20262E 100%)"
          : "linear-gradient(145deg, #F8FAFD 0%, #EEF3F8 100%)",
    },
    mediaPreviewAudio: {
      width: "100%",
    },
    mediaPreviewRemove: {
      position: "absolute",
      top: "0.5rem",
      right: "0.5rem",
      zIndex: 2,
      width: "1.9rem",
      height: "1.9rem",
      color: "#FFFFFF",
      backgroundColor: "rgba(0,0,0,0.56)",
      "&:hover": {
        backgroundColor: "rgba(0,0,0,0.72)",
      },
    },
    mediaList: {
      display: "flex",
      flexDirection: "column",
      gap: "0.55rem",
      width: "100%",
    },
    mediaGrid: (count) => ({
      display: "grid",
      gridTemplateColumns: count === 1 ? "1fr" : "repeat(2, minmax(0, 1fr))",
      gap: "0.45rem",
    }),
    mediaVisualItem: {
      overflow: "hidden",
      borderRadius: "0.85rem",
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#313844" : "#DCE3EC"),
      backgroundColor: "#000000",
    },
    mediaVisual: {
      display: "block",
      width: "100%",
      maxHeight: "16rem",
      minHeight: "8rem",
      objectFit: "cover",
      backgroundColor: "#000000",
    },
    mediaAudioItem: {
      borderRadius: "0.85rem",
      border: "1px solid",
      borderColor: (theme) => (theme.palette.mode === "dark" ? "#313844" : "#DCE3EC"),
      backgroundColor: (theme) => (theme.palette.mode === "dark" ? "#171A1F" : "#F8FAFD"),
      p: "0.65rem",
    },
    mediaAudio: {
      width: "100%",
    },
  },
};
