export const CLASS_TYPE = {
  POST_BY_ID:'post by id',
  STORY:'story',
  FEEDS:'feeds',
  FOLLOWERS_POST:'followers post',
  USERS_POST:'users post',
  SAVED_POST:'saved post',
  REACTION:'reaction',
  LOADING:'LOADING',
  HAS_MORE:'HAS MORE',
  PIN:"PIN"
}

export const LOADING = {
  GET_POST_LIST:"get post list",
  GET_SAVED_LIST:"get saved list",
  SET_POST_SAVE_LOADING: "set post save loading",
  SET_POST_PIN_LOADING: "set post pin loading",
  SET_CREATE_POST_LOADING: "set create post loading",
  SET_PRESIGN_LOADING: "set presign loading",
}

export const HAS_MORE = {
  SET_USERS_POST_HAS_MORE:'SET USER POSTS HAS MORE',
  INIT_USERS_POST_HAS_MORE:'INIT USER POSTS HAS MORE',
  SET_SAVED_HAS_MORE:'SET SAVED HAS MORE'
}

export const POST_BY_ID = {
  ADD_POSTS_BY_ID : 'ADD POST BY ID',
  ADD_POST_BY_ID: 'ADD POST BY ID ITEM',
  SET_POST_SAVED: 'SET POST SAVED',
  SET_POST_PINNED: 'SET POST PINNED'
}

export const STORY = {
  SET_STORY_LIST: 'SET STORY LIST',
  ADD_STORY_INDEX: 'ADD STORY INDEX',
  CLEAR_STORY_LIST: 'CLEAR STORY LIST'
}

export const USERS_POST = {
  ADD_TIMELINE_INDEX: "ADD USERS POST TIMELINE INDEX",
  PREPEND_TIMELINE_INDEX: "PREPEND USERS POST TIMELINE INDEX"
}

export const SAVED_POST = {
  ADD_TIMELINE_INDEX: "ADD SAVED POST TIMELINE INDEX",
  PREPEND_TIMELINE_INDEX: "PREPEND SAVED POST TIMELINE INDEX",
  REMOVE_TIMELINE_INDEX: "REMOVE SAVED POST TIMELINE INDEX"
}

export const REACTION = {
  SET_POST_REACTION: 'SET POST REACTION'
}

export const PIN = {
  SET_PIN_LIST:'SET PIN LIST'
}
