export const CLASS_TYPE = {
  POST_BY_ID:'post by id',
  STORY_BY_ID:'story by id',
  STORY:'story',
  FEEDS:'feeds',
  FOLLOWERS_POST:'followers post',
  USERS_POST:'users post',
  SAVED_POST:'saved post',
  REACTION:'reaction',
  LOADING:'LOADING',
  HAS_MORE:'HAS MORE',
  PIN:"PIN"
}

export const LOADING = {
  GET_POST_LIST:"get post list",
  GET_SAVED_LIST:"get saved list",
  SET_POST_SAVE_LOADING: "set post save loading",
  SET_POST_SHARE_LOADING: "set post share loading",
  SET_POST_PIN_LOADING: "set post pin loading",
  SET_CONTENT_DELETE_LOADING: "set content delete loading",
  SET_EDIT_POST_LOADING: "set edit post loading",
  SET_EDIT_STORY_LOADING: "set edit story loading",
  SET_CREATE_POST_LOADING: "set create post loading",
  SET_CREATE_STORY_LOADING: "set create story loading",
  SET_PRESIGN_LOADING: "set presign loading",
}

export const HAS_MORE = {
  SET_USERS_POST_HAS_MORE:'SET USER POSTS HAS MORE',
  INIT_USERS_POST_HAS_MORE:'INIT USER POSTS HAS MORE',
  SET_SAVED_HAS_MORE:'SET SAVED HAS MORE'
}

export const POST_BY_ID = {
  ADD_POSTS_BY_ID : 'ADD POST BY ID',
  ADD_POST_BY_ID: 'ADD POST BY ID ITEM',
  UPDATE_POST_BY_ID: 'UPDATE POST BY ID ITEM',
  SET_POST_SAVED: 'SET POST SAVED',
  SET_POST_SHARED: 'SET POST SHARED',
  SET_POST_PINNED: 'SET POST PINNED',
  REMOVE_POST_BY_ID: 'REMOVE POST BY ID ITEM',
}

export const STORY_BY_ID = {
  ADD_STORIES_BY_ID: 'ADD STORIES BY ID',
  ADD_STORY_BY_ID: 'ADD STORY BY ID ITEM',
  UPDATE_STORY_BY_ID: 'UPDATE STORY BY ID ITEM',
  SET_STORY_PINNED: 'SET STORY PINNED',
  REMOVE_STORY_BY_ID: 'REMOVE STORY BY ID ITEM',
}

export const STORY = {
  SET_STORY_LIST: 'SET STORY LIST',
  ADD_STORY_INDEX: 'ADD STORY INDEX',
  ADD_FRIEND_STORY_INDEX: 'ADD FRIEND STORY INDEX',
  PREPEND_STORY_INDEX: 'PREPEND STORY INDEX',
  CLEAR_STORY_LIST: 'CLEAR STORY LIST',
  CLEAR_FRIEND_STORY_LIST: 'CLEAR FRIEND STORY LIST',
  SET_PIN_STORY:"SET PIN STORY",
  PREPEND_CURRENT_STORY_INDEX:'PREPEND CURRENT STORY INDEX'
}

export const USERS_POST = {
  ADD_TIMELINE_INDEX: "ADD USERS POST TIMELINE INDEX",
  PREPEND_TIMELINE_INDEX: "PREPEND USERS POST TIMELINE INDEX",
  SET_TIMELINE_INDEX: "SET USERS POST TIMELINE INDEX",
  REMOVE_USERS_POST:'REMOVE_USERS_POST'
}

export const SAVED_POST = {
  ADD_TIMELINE_INDEX: "ADD SAVED POST TIMELINE INDEX",
  PREPEND_TIMELINE_INDEX: "PREPEND SAVED POST TIMELINE INDEX",
  REMOVE_TIMELINE_INDEX: "REMOVE SAVED POST TIMELINE INDEX"
}

export const REACTION = {
  SET_POST_REACTION: 'SET POST REACTION'
}

export const PIN = {
  SET_PIN_LIST:'SET PIN LIST'
}
