import {COLOR} from '../color'
const baseProps = {
  MuiTextField:{
    styleOverrides:{
      root:{
        width:'100%'
      }
    }
  }
}

export const textfieldProps = {
  ...baseProps,
  MuiInputBase:{
    styleOverrides:{
      input:({theme})=>({
        ...theme.typography.normal,
        color:COLOR.textfield.text.placeholder.dark,
        width:"100%"
      })
    }
  },
  MuiInputLabel:{
    styleOverrides:{
      root:({theme})=>({
        ...theme.typography.normal,
        marginBottom:'4px',
        color:COLOR.textfield.text.label.default[theme.palette.mode],
        '&.Mui-focused':{color:COLOR.textfield.text.label.focus[theme.palette.mode]},
      })
    }
  },
  MuiInput:{
    styleOverrides:{
      root:({theme})=>({
        '&:before':{borderBottomColor:COLOR.textfield.border.default},
        '&:after':{borderBottomColor:COLOR.textfield.border.after[theme.palette.mode]}
      })
    },
    variants:[
      {
        props:{variant:'loading'},
        style:({theme})=>({
          '&:before':{borderBottomColor:COLOR.textfield.border.default},
          '&:after':{borderBottomColor:COLOR.textfield.border.after[theme.palette.mode]}
        })
      }
    ]
  }
}