/**
 * Block Store Types
 * Define action types cho block feature
 */

export const CLASS_TYPES = {
  LOADING:'LOADING',
  BLOCK_LIST:'block list',
}

export const LOADING_TYPES = {
  SET_BLOCK_LIST_LOADING: 'SET_BLOCK_LIST_LOADING',
  SET_BLOCK_ACTION_LOADING: 'SET_BLOCK_ACTION_LOADING',
  GET_BLOCK_STATUS_LOADING: 'GET_BLOCK_STATUS_LOADING',
  CANCEL_BLOCK_LOADING:'CANCEL_BLOCK_LOADING'
}

export const BLOCK_LIST_TYPES = {
  SET_BLOCK_LIST: 'SET_BLOCK_LIST',
  REMOVE_BLOCKED_USER: 'REMOVE_BLOCKED_USER',
  SET_HAS_MORE: 'SET_HAS_MORE',
  ADD_BLOCKED_USER:'A_BLOCKED_USER',
  RESET:'RESET'
}